### PR TITLE
Uninstall elixirs; remove aliases.

### PR DESCRIPTION
**Pull request by greymouser**
* Added list of aliases per elixir version to `kiex list` output
* Add support for removing aliases
* Add support for uninstalling elixir versions (and associated aliases)
* Solves issue #39

### CODE REVIEW

**Comment by greymouser** [comment]
Happy to factor in any feedback. (I haven't heard anything in 14 days -- is this project still active?) Thanks!

**Comment by taylor** [comment]
Thanks @greymouser.  

I'd like to get tests in place at some point so it "feels" safer to pull in updates :)

**Comment by greymouser** [comment]
Nice! No, thank you, @taylor !

**Comment by taylor** [comment]
@greymouser reverted because of Bash 3.2 support needed for OS X.  See https://github.com/taylor/kiex/issues/63

**Pull request merged**
